### PR TITLE
Address compiler warnings

### PR DESCRIPTION
**Pull request by knedlsepp**
Hi!
First of all: Great tool you've got there!
Second: This PR addresses some warnings/errors that popped up when compiling with the C++11 standard.
Would you be interested in using cmake to automatically determine if all the dependencies are installed? I might contribute some more if you don't mind.

### CODE REVIEW

**Comment by knedlsepp** [comment]
It seems the current .travis.yml configuration is running on gcc<=4.7, which means that -std=c++11 is only recognized via std=c++0x. The script would need updating too. I tried it with my own  (https://github.com/knedlsepp/gridpp/blob/travis-changes/.travis.yml), which works, but it does not include the coveralls script at the moment.

**Comment by tnipen** [comment]
Thanks a lot for your work Josef! I appreciate the changes to get this compiling with c++11. I ran into a slight problem though, and that is that the code should run using gcc4.6 (we have some outdated systems...). Some of the changes, like using override, isn't supported by 4.6 (even when using -std=c++0x). Any recommendations for handling this situation?

**Comment by tnipen** [comment]
And yes, a proper way to handle dependencies with cmake is definitely on my wish list. Sadly I don't have a lot of experience with cmake, so if you are interested in starting out that would be great!

**Comment by knedlsepp** [comment]
Oh. This is unfortunate. I was actually also in the middle of removing all `new` and `delete`s and replacing them with `unique_ptr`s: https://github.com/knedlsepp/gridpp/commits/no-raw-owning-pointers, as this is now the recommended way to do it.
I suppose if you really need this to be compilable on gcc4.6 then I suppose it would be best to unmerge the changes. :-/
I personally get around the problem with legacy systems by not using the systems shipped compiler, but by installing the [nix](https://nixos.org/nix/) package manager and then install a current version of gcc or clang. This however requires quite a different workflow (despite all its upsides) and thus is probably not suited in your case.

**Pull request merged**
